.PHONY: clean

hw3: src/main.cpp test/ut_main.cpp test/ut_shape.cpp test/ut_sort.cpp src/shape.h src/sort.h src/circle.h src/rectangle.h src/triangle.h
	g++ src/main.cpp -o bin/hw3 -std=c++11

clean:
	rm -f bin/hw3
